name: Package

on:
  push:
    tags:
      - "*-beta"
      
jobs:
  "Package-and-deploy":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: BigWigsMods/packager@v2